<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<?php echo '<?xml-stylesheet type="text/xsl" href="../css/main-sitemap.xsl"?>'; ?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
 xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
@if($sitemaps->type=='post')

   @foreach ($posts as $post)

  
        <url>
          <loc>{{ post_path($post->id) }}</loc>
            <lastmod> {{ $post->updated_at->tz('UTC')->toAtomString() }}</lastmod>
            <changefreq>{{ $sitemaps->changefreq }}</changefreq>
            <priority>{{ $sitemaps->priority }}</priority>
        </url>




    @endforeach

    @elseif($sitemaps->type=='tag')
@foreach ($posts as $post)
        <url>
            <loc>{{ url('/')}}{{ $post->path }}</loc>
            <lastmod> {{ $post->updated_at->tz('UTC')->toAtomString() }}</lastmod>
            <changefreq>{{ $sitemaps->changefreq }}</changefreq>
            <priority>{{ $sitemaps->priority }}</priority>
        </url>
    @endforeach

   @else

   @foreach ($posts as $post)
        <url>
            <loc>{{ route('page_single', $post->slug ) }}/</loc>
            <lastmod> {{ $post->updated_at->tz('UTC')->toAtomString() }}</lastmod>
            <changefreq>{{ $sitemaps->changefreq }}</changefreq>
            <priority>{{ $sitemaps->priority }}</priority>
        </url>
    @endforeach

    @endif
 
</urlset>
<!-- XML Sitemap generated by STARLINK KENYA SEO -->
