<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<?php echo '<?xml-stylesheet type="text/xsl" href="../css/main-sitemap.xsl"?>'; ?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    @foreach ($posts as $post)
    <?php
    $datetime = new DateTime($post->updated_at);
    ?>
    {{-- @dd($post); --}}
    <sitemap>
        {{-- <loc>{{$post->url}}</loc> --}}
        <loc>{{ route('page_single', $post->url ) }}</loc>
        <lastmod>{{ $datetime->format(DateTime::ATOM) }}</lastmod>
    </sitemap>
    @endforeach
</sitemapindex>
<!-- XML Sitemap generated by STARLINK KENYA SEO -->